# Generated by Django 4.1 on 2022-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywatchlist',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
